% Electrolyzer_model object testing
clear; clc; close all;
addpath("Utils");

T = 285;
obj = electrolyzer_model("type", "alkaline", "electrolyte", "KOH") ...
    .add_overpotential(nernst(T, 1, 10, "type", "alkaline", "electrolyte", "KOH")) ...
    .add_overpotential(ohmic('type', 'alkaline')) ...
    .add_overpotential(activation(T)) ...
    .add_overpotential(concentration(T)) ...
    .combine_overpotentials() ...
    .show_UI();


%%
%uniqueArguments = obj.getOverpotentialArguments()
obj.combine_overpotentials()
obj.overpotential_function
obj.overpotential_function(0.5, 1e-6, 2, 10, 4)